### ISSUE TITLE
Incorrect date value on related list

### ISSUE THREAD

**Issue by catherine-aujongSFDC** [CynoteckLabs/CTK-LightningComponentSupport#10]
**Describe the bug**
The date value presented on the related list is always D-1 compared to the actual data stored.

**To Reproduce**
1. Select a date on the record (1/1/2020)
2. Open the related list

**Expected behavior**
Date shown as 1/1/2020 on the related list

**Screenshots**
![image](https://user-images.githubusercontent.com/123204350/213788663-d02eb00f-272b-4023-b460-01259c3eed87.png)
![image](https://user-images.githubusercontent.com/123204350/213788693-93e838bc-7dd1-4b15-a210-5d3bd72482c1.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Chrome
 - Version 109.9.5414.87

**Comment by toanshulverma** [comment]
@aujongc : Currently, the grid displays date-time value based on logged in user's locale (timezone) settings.

Please share actual date values that you get, when you retrieve them via an SOQL query?

**Comment by catherine-aujongSFDC** [comment]
Anshul,

Here is the date value on the related list:
[image: image.png]

And here is the date value on the actual record:
[image: image.png]

Here is the SOQL Query:
[image: image.png]

User is on Eastern timezone:
[image: image.png]

The date on the SOQL Query and on the record shows 2023-01-01 but the
Related list is showing 2022-12-31

**Comment by toanshulverma** [comment]
@aujongc  : Images are missing. Can you upload them again (directly into github)?

**Comment by catherine-aujongSFDC** [comment]
Anshul,

Here is the date value on the related list:
![image](https://user-images.githubusercontent.com/123204350/214361956-7babdbce-4c94-4bfb-bfdb-ad08672f7dae.png)


And here is the date value on the actual record:
![image](https://user-images.githubusercontent.com/123204350/214361985-354ed9c6-af6c-42d4-a9a0-3f6cd6bc8635.png)


Here is the SOQL Query:
![image](https://user-images.githubusercontent.com/123204350/214362015-9a29e6b9-aa1c-45d9-8e50-a5b03937a11d.png)

User is on Eastern timezone: 
![image](https://user-images.githubusercontent.com/123204350/214362038-0a374056-2ebd-48c5-acf7-f09882fc9463.png)

The date on the SOQL Query and on the record shows 2023-01-01 but the Related list is showing 2022-12-31

**Comment by toanshulverma** [comment]
@aujongc  : Sorry, details provided are not adequate and have lot of gaps. Can you perform following:
1. Identify few test records  with date values and send screenshot of SOQL Query for these records
2. Create a related list using CTK Dynamic Related list component and other using standard related list (to compare it with standard related list values)
3. Send screenshot of Salesforce page, showing both related lists (as in step 2) for same records as per Step 1

**Comment by catherine-aujongSFDC** [comment]
Identify few test records with date values and send screenshot of SOQL Query for these records
![Screenshot 2023-01-24 at 5 01 49 PM](https://user-images.githubusercontent.com/123204350/214440373-0b9b2967-8458-44d2-9906-cd22dd393e0f.png)
![image](https://user-images.githubusercontent.com/123204350/214440472-2fedf9ea-51cc-4e1c-883c-bc64f871f70d.png)


Create a related list using CTK Dynamic Related list component and other using standard related list (to compare it with standard related list values)
CTK Dynamic Related List:
![image](https://user-images.githubusercontent.com/123204350/214440501-65638c56-f9c4-418b-871b-9f5b68acdf50.png)

Standard Related List: 
![image](https://user-images.githubusercontent.com/123204350/214440678-7cbf9585-a81f-4b96-8725-75b84fe7dd44.png)


Send screenshot of Salesforce page, showing both related lists (as in step 2) for same records as per Step 1
![image](https://user-images.githubusercontent.com/123204350/214440807-4455c9d7-a8ec-4b52-809d-78b246aa36f7.png)

**Comment by toanshulverma** [comment]
@aujongc  : We have released a new version which has additional format fixes and features. Please review it and report back, if this is still an issue.

**Comment by nikhil9980** [comment]
Hi @toanshulverma ,

when i try for installation it is asking for installation key 
![image](https://user-images.githubusercontent.com/63646087/220309976-1b4bb34b-d599-420d-8db4-96feb35686fb.png)

**Comment by anshumanctk** [comment]
> Hi @toanshulverma ,
> 
> when i try for installation it is asking for installation key ![image](https://user-images.githubusercontent.com/63646087/220309976-1b4bb34b-d599-420d-8db4-96feb35686fb.png)

Hi @nikhil9980 ,
 We have released a latest version yesterday that will not ask for installation key. Please try installing it now.

**Comment by toanshulverma** [comment]
Closing this issue, as new comments are unrelated to the issue.
