### ISSUE TITLE
Filters - Contains instead of Equals

### ISSUE THREAD

**Issue by LingChong83** [CynoteckLabs/CTK-LightningComponentSupport#12]
Hello!

This is working for me except I need to use "Contains" statements instead of "Equals", or multiple equals statements.

I have a List View which is currently filtered by:-

accountId = '[id]' and Subject = 'NB Phone Meeting'

However, I need it to also capture Subject = 'NB Live Meeting', so basically the list view is filtered/shows by the Account ID and only when the Subject contains NB Meeting.

Is there a way of doing this?  Apologies as I am not a developer and have zero SOQL experience.  I have tried the below and different variations but cannot get it to work:-
 
accountId = '[id]' and Subject = 'NB Phone Meeting' OR 'NB Live Meeting'

Thanks!

**Comment by mk8837** [comment]
Hi @LingChong83 ,

Noticed a minor issue with your filter for using multiple equal statements. You might want to try this instead:
accountId = '[id]' AND (Subject = 'NB Phone Meeting' OR Subject ='NB Live Meeting')
Please let us know if this resolves the issue for you.

**Comment by toanshulverma** [comment]
@LingChong83  : You may want to look at using Like operator (Refer: https://developer.salesforce.com/docs/atlas.en-us.soql_sosl.meta/soql_sosl/sforce_api_calls_soql_select_comparisonoperators.htm)

For example: accountId = '[id]' and Subject LIKE 'NB%Meeting'

**Comment by toanshulverma** [comment]
Closing this ticket, as there's no action needed for component.
