### ISSUE TITLE
Sort Descending checkbox has no effect

### ISSUE THREAD

**Issue by LouEss** [CynoteckLabs/CTK-LightningComponentSupport#3]
**Describe the bug**
Checking the Sort Descending checkbox has no effect.  The entered Sort by field is always sorted ascending on load.  Tried a few different fields, always the same result.

**To Reproduce**
1. Enter a field in the Sort by attribute and step off the field
2. Note the field is sorted ascending
3. Check the Sort Descending field
4. Note the field is still sorted ascending
5. Save, exit page edit and load the page, verify still ascending

**Expected behavior**
The records should be sorted by the Sort by field descending when the Sort Descending box is checked

**Screenshots**
![image](https://user-images.githubusercontent.com/95060049/143515317-b0234f98-525b-4dde-9eb4-12efe5d01fd8.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser:  Chrome 95.0.4638.69
 - Version 0.1

**Smartphone (please complete the following information):**
  - NA

**Comment by toanshulverma** [comment]
Thanks for the patient. This is being fixed in upcoming release.

**Comment by toanshulverma** [comment]
@LouEss This issue is fixed in latest release. Please review and report back if there are still any issues
https://appexchange.salesforce.com/listingDetail?listingId=a0N4V00000FgsCCUAZ
