### ISSUE TITLE
Question on Soql filter

### ISSUE THREAD

**Issue by rhernandezblueocean** [CynoteckLabs/CTK-LightningComponentSupport#5]
I was able to show the related list and  its great.  However, it is showing ALL records.  I want to filter it only by the current record page (e.g.the current page is a task record and “Name” is the lookup to contact/lead.   I want to match this with the related list record object who’s ID is Contactid__c.

This should be a quick solution so kindly contact me at 604-506-3313.  Thank you so much for your help

**Comment by shubham25Bisht** [comment]
@rhernandezblueocean: We are available during IST. Please share your preferred time. In the meantime, Lets take an example where I need to display related contacts under Account. In the attached screenshot I have applied filters **accountId='[id]'** where accountId is the look up field(you can use this field that holds current page record id) in Contact and '[Id]' always holds the current record id here it will hold current Account Id. 
<img width="694" alt="ScreenShot" src="https://user-images.githubusercontent.com/71754622/161699660-6f6d2c1f-6bbb-4270-877a-050ff4d54dea.png">

**Comment by rhernandezblueocean** [comment]
Thank you for your quick reply.  I am still not able to get the filter to work.  

I am in PST.  At the moment it is 7:00am in the morning.    I can be available at 10:00pm PST tonight.  Would you be available then?

Thank you

**Comment by toanshulverma** [comment]
@rhernandezblueocean  : Please refer to Sample use cases within the user guide (https://github.com/CynoteckLabs/CTK-LightningComponentSupport/wiki/CTK-Dynamic-Related-List---Usage-Guide)

**Comment by rhernandezblueocean** [comment]
Yes I have already reviewed the wiki.  Thank you.
Can we have 15 minutes to chat?

**Comment by rhernandezblueocean** [comment]
Hi there, just following up @shubham25Bisht.  Please let me know what time works best for you.  I am in pacific timezone.

**Comment by rhernandezblueocean** [comment]
@toanshulverma and @shubham25Bisht - kindly respond please.  This inquiry should not take too long.  I just need help with the filter.  Need a 10 minute conversation.

**Comment by rhernandezblueocean** [comment]
@shubham25Bisht I am available right now if you are as it is morning for you

**Comment by rhernandezblueocean** [comment]
May I ask for updates please?  Who can we escalate this to?

**Comment by rhernandezblueocean** [comment]
Please respond.

**Comment by rhernandezblueocean** [comment]
@shubham25Bisht @toanshulverma - Hi, may we please receive an update?  Or just a quick 5 minute discussion?

**Comment by toanshulverma** [comment]
@rhernandezblueocean  : As we understand, the filters would need to be configured based on your target data and fields. The sample for same has been provided within documentation (https://github.com/CynoteckLabs/CTK-LightningComponentSupport/wiki/CTK-Dynamic-Related-List---Usage-Guide). Please refer to that for more guidance. If there are any gaps within documentation, please highlight, so we can improve content accordingly.

Assuming this is an old issue and should have been resolved at your end, we are closing this.
