### ISSUE TITLE
'View all' link?

### ISSUE THREAD

**Issue by CareerReadyUK** [CynoteckLabs/CTK-LightningComponentSupport#6]
Is it possible to include a 'view all' link to view the complete related list beyond the default five, as you might with a standard related list?

**Comment by toanshulverma** [comment]
@CareerReadyUK  : We are adding this to upcoming release. Thanks for your patience.

**Comment by toanshulverma** [comment]
@CareerReadyUK : This feature is implemented in latest release. Please review and report back if there are still any issues
https://appexchange.salesforce.com/listingDetail?listingId=a0N4V00000FgsCCUAZ

**Comment by nikhil9980** [comment]
why im uanable to install it is asking for installation key
