### ISSUE TITLE
Typo in Usage guide > Attributes > Filters > Example: double vs single quotes?

### ISSUE THREAD

**Issue by juhalassila** [CynoteckLabs/CTK-LightningComponentSupport#7]
In documentation double quotes are specified
- accountid="[id]" OR account.ParentId="[id]"

However, when configuring the component in "Edit Page":

... filter with double quotes does not return records
- SplitOwnerId="[id]"

... filter with single quotes returns records
- SplitOwnerId='[id]'

**Comment by toanshulverma** [comment]
@juhalassila  : Thanks for highlighting. This is fixed and closed.
