### ISSUE TITLE
Percentage 12,30% in Opportunity Split shows up as  1 230 %

### ISSUE THREAD

**Issue by juhalassila** [CynoteckLabs/CTK-LightningComponentSupport#8]
NOTE: User locale is Finnish (Finland, Euro)
- could have impact on how decimal point and thousand separators are handled?

I have an Opportunity Split with 12,30%
![image](https://user-images.githubusercontent.com/26527282/212459860-1bf41c33-b004-4ae6-ab38-24d5b6bab004.png)

In component it shows up as 1 230% (= 100 x 12,30%)
![image](https://user-images.githubusercontent.com/26527282/212459972-2b160097-848f-4067-8098-9f1e0ca186bf.png)

**Comment by toanshulverma** [comment]
@juhalassila : Thanks for reporting this. Out team is looking into this. Will update in some time.

**Comment by toanshulverma** [comment]
@juhalassila This issue is fixed in latest release. Please review and report back if there are still any issues
https://appexchange.salesforce.com/listingDetail?listingId=a0N4V00000FgsCCUAZ
